<a href="https://colab.research.google.com/github/AR-Ashik-9997/Phitron-practice-problem/blob/main/NLP_TFIDF_Module_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset

In [69]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [70]:
nltk.download('punkt_tab')
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [71]:
df=pd.read_csv("/content/spam.csv",encoding='latin-1')
df

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [72]:
df=df[["v1","v2"]]
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [73]:
df['v2'][0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [74]:
# Problem 1

# Apply all the preprocessing techniques that you've leanred from the NLP Modules
def preprocess_sms(text):
  text=text.lower()
  text = re.sub(r'https?://\S+|www\.\S+', '', text)
  text=re.sub(r'<.*?>','',text)
  text=re.sub(r'__+',' ',text)
  text=re.sub(r'[^a-z\s]',' ',text)
  text=re.sub(r'\s+',' ',text).strip()
  tokens=word_tokenize(text)
  return " ".join(tokens)

In [75]:
df['cleaned_text'] = df['v2'].apply(preprocess_sms)

/tmp/ipykernel_1584/4158452264.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cleaned_text'] = df['v2'].apply(preprocess_sms)

In [94]:
df['cleaned_text'].head()

0    go until jurong point crazy available only in ...
1                              ok lar joking wif u oni
2    free entry in a wkly comp to win fa cup final ...
3          u dun say so early hor u c already then say
4    nah i don t think he goes to usf he lives arou...
Name: cleaned_text, dtype: object

In [96]:
corpus=df['cleaned_text'].tolist()

In [78]:
# Problem 2

# Find out the number of words in the entire corpus and also the total number of unique words(vocabulary) using just python

all_token=[word for doc in corpus for word in doc.split()]
total_words=len(all_token)
unique_vocabulary=set(all_token)
uniquq_words=len(unique_vocabulary)

print(f"Total words in corpus: {total_words}")
print(f"Total unique words (Vocabulary): {uniquq_words}")

Total words in corpus: 86550
Total unique words (Vocabulary): 7658

In [79]:
# Problem 3

# Apply One Hot Encoding

encoding=CountVectorizer(binary=True)
X_ohe=encoding.fit_transform(corpus)
X_ohe.shape

(5572, 7632)

In [88]:
# Problem 4

# Apply bag words and find the vocabulary also find the times each word has occured
bag_of_words=CountVectorizer()
X=bag_of_words.fit_transform(corpus)
vocab=bag_of_words.get_feature_names_out()

word_counts=X.sum(axis=0).A1
vocab_freq=dict(zip(vocab,word_counts))

print(f"vocab size:{len(vocab)}")
for word,freq in list(vocab_freq.items())[:10]:
  print(f"'{word}':{freq} times")

vocab size:7632
'aa':1 times
'aah':3 times
'aaniye':1 times
'aaooooright':1 times
'aathi':6 times
'ab':1 times
'abbey':1 times
'abdomen':1 times
'abeg':1 times
'abel':1 times

In [90]:
# Problem 5

# Apply bag of bi-gram and bag of tri-gram and write down your observation about the dimensionality of the vocabulary

bi_gram=CountVectorizer(ngram_range=(2,2))
X_bigram=bi_gram.fit_transform(corpus)
tri_gram=CountVectorizer(ngram_range=(3,3))
X_trigram=tri_gram.fit_transform(corpus)

print(f"Bigram Vocab Size: {len(bi_gram.vocabulary_)}")
print(f"Trigram Vocab Size: {len(tri_gram.vocabulary_)}")

Bigram Vocab Size: 39828
Trigram Vocab Size: 52357

In [93]:
# Problem 6

# Apply tf-idf and find out the idf scores of words

tf_idf=TfidfVectorizer()
X_tfidf=tf_idf.fit_transform(corpus)

idf_scores=dict(zip(tf_idf.get_feature_names_out(),tf_idf.idf_))

for word,score in list(idf_scores.items())[:10]:
  print(f"{word}: {score:.4f}")

aa: 8.9325
aah: 8.2394
aaniye: 8.9325
aaooooright: 8.9325
aathi: 7.6798
ab: 8.9325
abbey: 8.9325
abdomen: 8.9325
abeg: 8.9325
abel: 8.9325