<a href="https://colab.research.google.com/github/AR-Ashik-9997/Phitron-practice-problem/blob/main/simple_ANN_with_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [245]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [246]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [247]:
df.shape

(569, 33)

In [248]:
df.drop(columns=['id','Unnamed: 32'],axis=1,inplace=True)

In [249]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [250]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [251]:
y_train

222    B
520    B
369    M
241    B
176    B
      ..
501    M
94     M
380    B
228    B
295    B
Name: diagnosis, Length: 455, dtype: object

In [252]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [253]:
y_train

array([0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0])

In [254]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [255]:
X_train_tensor.shape

torch.Size([455, 30])

In [256]:
y_train_tensor.shape

torch.Size([455])

In [257]:
class MySimpleNN():

  def __init__(self,X):
    self.weight=torch.rand(X.shape[1],dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward_function(self,X):
    Z=torch.matmul(X,self.weight)+self.bias
    y_pred=torch.sigmoid(Z)
    return y_pred

  def loss_function(self,y_pred,y):
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)
    loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss

In [258]:
learning_rate=0.1
epochs=25

model=MySimpleNN(X_train_tensor)

for epoch in range(epochs):
  y_pred=model.forward_function(X_train_tensor)
  loss=model.loss_function(y_pred,y_train_tensor)

  loss.backward()

  with torch.no_grad():
    model.weight -=learning_rate*model.weight.grad
    model.bias -=learning_rate*model.bias.grad

    model.weight.grad.zero_()
    model.bias.grad.zero_()

    print(f"Epoch:{epoch+1},Loss:{loss.item()}")

Epoch:1,Loss:0.3504801168587207
Epoch:2,Loss:0.33899085567277676
Epoch:3,Loss:0.32788388239827176
Epoch:4,Loss:0.31713955058136467
Epoch:5,Loss:0.30673914617380516
Epoch:6,Loss:0.2966661135744212
Epoch:7,Loss:0.28690686827420214
Epoch:8,Loss:0.2774511871733618
Epoch:9,Loss:0.2682922433321412
Epoch:10,Loss:0.2594263704283621
Epoch:11,Loss:0.25085262976830625
Epoch:12,Loss:0.24257223143868095
Epoch:13,Loss:0.23458784890867163
Epoch:14,Loss:0.22690286466214238
Epoch:15,Loss:0.21952059335515806
Epoch:16,Loss:0.2124435423385877
Epoch:17,Loss:0.20567277764081218
Epoch:18,Loss:0.19920746471028683
Epoch:19,Loss:0.19304463233577154
Epoch:20,Loss:0.18717918050388838
Epoch:21,Loss:0.18160411529671644
Epoch:22,Loss:0.1763109616272658
Epoch:23,Loss:0.17129028461357043
Epoch:24,Loss:0.1665322460143201
Epoch:25,Loss:0.16202713100807814

In [259]:
model.bias

tensor([-0.0590], dtype=torch.float64, requires_grad=True)

# Evalution

In [260]:
with torch.no_grad():
  y_pred=model.forward_function(X_test_tensor)
  y_pred=(y_pred>0.9).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f"Accuracy:{accuracy.item()*100}")

Accuracy:92.1052634716034